# title: Find the Difference
# description: You are given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.
# difficulty: Easy

class Solution(object):
    def findTheDifference(self, s, t):
        seen={}
        for i in t:
            if i not in seen:
                seen[i]=1
            else:
                seen[i]+=1
        for i in s:
            if i in seen:
                seen[i] -=1
        for key, values in seen.items():
            if values == 1:
                return key   
            
# The idea is to use a dictionary to count the occurrences of each character in string t.
# We first iterate through string t and populate the dictionary with character counts.
# Then, we iterate through string s and decrement the count for each character found in s.
# Finally, we check the dictionary for the character that has a count of 1, which is the added character in t.
#core logic-- dictionary + iteration